FROM maven:3.8-openjdk-17 as maven
COPY ./oauth/pom.xml ./pom.xml
COPY ./oauth/src ./src
RUN mvn clean package -Dmaven.test.skip=true -q
EXPOSE 8081
ENTRYPOINT ["java","-jar","./target/oauth-0.0.1-SNAPSHOT.jar"]